import type { Approval } from '../types';

export const seedApprovals: Approval[] = [
  // Approved bills history
  {
    id: 'APR-001',
    billId: 'BILL-0022',
    approverId: 'usr-002',
    approverName: 'Rajesh Iyer',
    action: 'Approved',
    timestamp: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'APR-002',
    billId: 'BILL-0023',
    approverId: 'usr-003',
    approverName: 'Ananya Gupta',
    action: 'Approved',
    timestamp: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'APR-003',
    billId: 'BILL-0024',
    approverId: 'usr-004',
    approverName: 'Vikram Patel',
    action: 'Approved',
    timestamp: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'APR-004',
    billId: 'BILL-0025',
    approverId: 'usr-005',
    approverName: 'Meera Reddy',
    action: 'Approved',
    timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'APR-005',
    billId: 'BILL-0026',
    approverId: 'usr-001',
    approverName: 'Sai Krishna S',
    action: 'Approved',
    timestamp: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'APR-006',
    billId: 'BILL-0044',
    approverId: 'usr-004',
    approverName: 'Vikram Patel',
    action: 'Approved',
    timestamp: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'APR-007',
    billId: 'BILL-0045',
    approverId: 'usr-005',
    approverName: 'Meera Reddy',
    action: 'Approved',
    timestamp: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  // Rejected bills
  {
    id: 'APR-008',
    billId: 'BILL-0059',
    approverId: 'usr-004',
    approverName: 'Vikram Patel',
    action: 'Rejected',
    reason: 'Budget limit exceeded for Q3. Please resubmit with revised amounts.',
    timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'APR-009',
    billId: 'BILL-0060',
    approverId: 'usr-005',
    approverName: 'Meera Reddy',
    action: 'Rejected',
    reason: 'Duplicate invoice — already processed under INV-20260055.',
    timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'APR-010',
    billId: 'BILL-0061',
    approverId: 'usr-001',
    approverName: 'Sai Krishna S',
    action: 'Rejected',
    reason: 'Vendor contract expired. Pending renewal before payment.',
    timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'APR-011',
    billId: 'BILL-0062',
    approverId: 'usr-002',
    approverName: 'Rajesh Iyer',
    action: 'Rejected',
    reason: 'Missing supporting documentation. Please attach purchase order.',
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'APR-012',
    billId: 'BILL-0063',
    approverId: 'usr-003',
    approverName: 'Ananya Gupta',
    action: 'Rejected',
    reason: 'Incorrect GST classification. Hardware purchase billed under services.',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
