import type { Reimbursement } from '../types';

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}

export const seedReimbursements: Reimbursement[] = [
  {
    id: 'RMB-001',
    employeeName: 'Aditya Menon',
    employeeEmail: 'aditya.menon@spendflow.in',
    amount: 12500,
    currency: 'INR',
    description: 'Client dinner at Taj Bangalore — product demo follow-up',
    category: 'Meals',
    receiptUrl: '/receipts/rmb-001.jpg',
    status: 'Paid',
    submittedAt: daysAgo(30),
    reviewedAt: daysAgo(27),
    reviewerName: 'Priya Sharma',
  },
  {
    id: 'RMB-002',
    employeeName: 'Kavitha Nair',
    employeeEmail: 'kavitha.nair@spendflow.in',
    amount: 45000,
    currency: 'INR',
    description: 'Flight BLR-DEL-BLR for annual sales conference',
    category: 'Travel',
    receiptUrl: '/receipts/rmb-002.jpg',
    status: 'Paid',
    submittedAt: daysAgo(25),
    reviewedAt: daysAgo(22),
    reviewerName: 'Rajesh Iyer',
  },
  {
    id: 'RMB-003',
    employeeName: 'Rohan Das',
    employeeEmail: 'rohan.das@spendflow.in',
    amount: 8900,
    currency: 'INR',
    description: 'Ergonomic keyboard and mouse for home office setup',
    category: 'Equipment',
    receiptUrl: '/receipts/rmb-003.jpg',
    status: 'Approved',
    submittedAt: daysAgo(18),
    reviewedAt: daysAgo(15),
    reviewerName: 'Ananya Gupta',
  },
  {
    id: 'RMB-004',
    employeeName: 'Sneha Kulkarni',
    employeeEmail: 'sneha.kulkarni@spendflow.in',
    amount: 3200,
    currency: 'INR',
    description: 'Uber rides for client meetings — September week 1',
    category: 'Travel',
    status: 'Approved',
    submittedAt: daysAgo(14),
    reviewedAt: daysAgo(12),
    reviewerName: 'Vikram Patel',
  },
  {
    id: 'RMB-005',
    employeeName: 'Arjun Mehta',
    employeeEmail: 'arjun.mehta@spendflow.in',
    amount: 15000,
    currency: 'INR',
    description: 'Online course — Advanced Data Analytics certification',
    category: 'Training',
    receiptUrl: '/receipts/rmb-005.jpg',
    status: 'Pending',
    submittedAt: daysAgo(10),
  },
  {
    id: 'RMB-006',
    employeeName: 'Divya Rajan',
    employeeEmail: 'divya.rajan@spendflow.in',
    amount: 6700,
    currency: 'INR',
    description: 'Team lunch for sprint retrospective celebration',
    category: 'Meals',
    receiptUrl: '/receipts/rmb-006.jpg',
    status: 'Pending',
    submittedAt: daysAgo(8),
  },
  {
    id: 'RMB-007',
    employeeName: 'Nikhil Saxena',
    employeeEmail: 'nikhil.saxena@spendflow.in',
    amount: 22000,
    currency: 'INR',
    description: 'Adobe Creative Cloud annual subscription for design team',
    category: 'Software',
    receiptUrl: '/receipts/rmb-007.jpg',
    status: 'Pending',
    submittedAt: daysAgo(6),
  },
  {
    id: 'RMB-008',
    employeeName: 'Anita Deshmukh',
    employeeEmail: 'anita.deshmukh@spendflow.in',
    amount: 4500,
    currency: 'INR',
    description: 'Office stationery and printing supplies for Q3 reports',
    category: 'Office Supplies',
    status: 'Pending',
    submittedAt: daysAgo(5),
  },
  {
    id: 'RMB-009',
    employeeName: 'Siddharth Joshi',
    employeeEmail: 'siddharth.joshi@spendflow.in',
    amount: 35000,
    currency: 'INR',
    description: 'Hotel stay (4 nights) Hyderabad for client onboarding',
    category: 'Travel',
    receiptUrl: '/receipts/rmb-009.jpg',
    status: 'Pending',
    submittedAt: daysAgo(4),
  },
  {
    id: 'RMB-010',
    employeeName: 'Preethi Venkat',
    employeeEmail: 'preethi.venkat@spendflow.in',
    amount: 78000,
    currency: 'INR',
    description: 'External monitor and docking station for engineering team lead',
    category: 'Equipment',
    receiptUrl: '/receipts/rmb-010.jpg',
    status: 'Rejected',
    submittedAt: daysAgo(12),
    reviewedAt: daysAgo(9),
    reviewerName: 'Meera Reddy',
  },
  {
    id: 'RMB-011',
    employeeName: 'Karthik Sundaram',
    employeeEmail: 'karthik.sundaram@spendflow.in',
    amount: 2800,
    currency: 'INR',
    description: 'Parking fees and tolls for customer visits — August',
    category: 'Travel',
    status: 'Paid',
    submittedAt: daysAgo(20),
    reviewedAt: daysAgo(17),
    reviewerName: 'Priya Sharma',
  },
  {
    id: 'RMB-012',
    employeeName: 'Lakshmi Prasad',
    employeeEmail: 'lakshmi.prasad@spendflow.in',
    amount: 9500,
    currency: 'INR',
    description: 'Figma team plan upgrade — monthly subscription',
    category: 'Software',
    receiptUrl: '/receipts/rmb-012.jpg',
    status: 'Approved',
    submittedAt: daysAgo(7),
    reviewedAt: daysAgo(5),
    reviewerName: 'Rajesh Iyer',
  },
  {
    id: 'RMB-013',
    employeeName: 'Manish Tripathi',
    employeeEmail: 'manish.tripathi@spendflow.in',
    amount: 18500,
    currency: 'INR',
    description: 'AWS certification exam fee and study materials',
    category: 'Training',
    receiptUrl: '/receipts/rmb-013.jpg',
    status: 'Pending',
    submittedAt: daysAgo(3),
  },
  {
    id: 'RMB-014',
    employeeName: 'Rashmi Bhat',
    employeeEmail: 'rashmi.bhat@spendflow.in',
    amount: 5600,
    currency: 'INR',
    description: 'Team building activity expenses — bowling and snacks',
    category: 'Other',
    status: 'Pending',
    submittedAt: daysAgo(2),
  },
  {
    id: 'RMB-015',
    employeeName: 'Varun Agarwal',
    employeeEmail: 'varun.agarwal@spendflow.in',
    amount: 42000,
    currency: 'INR',
    description: 'International conference registration — React Summit Amsterdam',
    category: 'Training',
    receiptUrl: '/receipts/rmb-015.jpg',
    status: 'Pending',
    submittedAt: daysAgo(1),
  },
  {
    id: 'RMB-016',
    employeeName: 'Deepa Krishnan',
    employeeEmail: 'deepa.krishnan@spendflow.in',
    amount: 1200,
    currency: 'INR',
    description: 'Cab fare for late-night production deployment support',
    category: 'Travel',
    status: 'Approved',
    submittedAt: daysAgo(9),
    reviewedAt: daysAgo(7),
    reviewerName: 'Ananya Gupta',
  },
];
